### ISSUE TITLE
Error with '/ui/core/view/' Nativescript module

### ISSUE THREAD

**Issue by Jferra** [bradmartin/nativescript-gif#10]
Hello,

I'm trying to use your library in a Nativescript  - TypeScript/Angular project.

I imported it in the right component :

```javascript
import { Gif } from "nativescript-gif";
import { registerElement } from "nativescript-angular/element-registry";

registerElement("Gif", () => require("nativescript-gif").Gif );
```

```html
<StackLayout class="page">
  <Gif [src]="imageSrc$ | async" id="randomImage"></Gif>
</StackLayout>
```

When I try to run my app with tns, I'm getting this error : 
```
node_modules/nativescript-gif/gif.d.ts(40,43): error TS2694: Namespace '"ui/core/view"' has no exported member 'Options'.
```

I looked into Nativescript's **_/ui/core/view/_** module and indeed there is no **Options** member.

I used a starter from Nativescript to init my project using this command :
```
tns create MyApp --ng
```

**Versions :**
- nativescript : 2.5.1
- nativescript-angular : 1.4.0
- typescript : 2.1.6

Thanks in advance for your support :)

**Comment by bradmartin** [comment]
For now just turn off noEmitOnError in tsconfig.json to build and run. The definition file needs to be cleaned up and I'll try to do that later

**Comment by bradmartin** [comment]
Haven't published the update but the definition file https://github.com/bradmartin/nativescript-gif/blob/master/gif.d.ts has been updated. Should not see that TS error anymore.

**Comment by Jferra** [comment]
Thanks for your quick intervention !
