### ISSUE TITLE
Gif image is not showing up in iOS

### ISSUE THREAD

**Issue by nvp159** [bradmartin/nativescript-gif#18]

**Comment by slsumathi** [comment]
In case the Gif image is placed locally in app directory, gif image is not shown up in iOS divices.
Where as if we give https link for gif image its working in iOS.

In case of android its working for both local and https images.

This needs correction in iOS while handing local gif images ( not https urls )

Sumathi ( lsumathi_s@yahoo.in )

**Comment by slsumathi** [comment]
Brad,

  I fixed this issue. If you can give me permission I can submit the fix in github

**Comment by bradmartin** [comment]
Submit a PR and I'll merge it soon. Thanks

**Comment by slsumathi** [comment]
Thank you Brad. I created PR.

**Comment by bradmartin** [comment]
3.1.1 published to npm
