### ISSUE TITLE
Autoplay 

### ISSUE THREAD

**Issue by andreysuha2** [bradmartin/nativescript-gif#23]
Hi, how i can disabled autoplay on gif?

**Comment by bradmartin** [comment]
Possible approach would be to use the `loaded` event of the view which will provide `args.object` as the `Gif` instance. Which you can call `stop()` on to stop the playback of the .gif

**Comment by VeeK727** [comment]
Hi @bradmartin, can you share an example on how to use the loaded event? Better yet, add the example to readme. I think its needed. Here's what I tried
```
exports.onLoaded = function(args) {
  page = args.object;
  var checkMark = view.getViewById(page, "checkmark");
  checkMark.onLoaded(function(){
    console.log('gifloaded ');
  })
}

exports.gifLoaded = function(){
  console.log('loaded gif');
}
```
Both didn't fire.
