### ISSUE TITLE
Animated gif not loading with src parameter as res://

### ISSUE THREAD

**Issue by sivaprasad-kiranum** [bradmartin/nativescript-gif#32]
The animated gif is not loading then the src parameter is given as res://

<Gif src="res://bill.gif" height="200"></Gif>

**Comment by TySabs** [comment]
It looks like there is a bug with webpack not bundling .gif files. Try renaming your gif file as .png and navigate from the root using '~'

**Comment by bradmartin** [comment]
I don't think that's a "bug", that to me indicates the webpack config isn't configured correctly. Granted, this should be documented on the README for the plugin 😄 

```javascript
      // Copy assets to out dir. Add your own globs as needed.
      new CopyWebpackPlugin(
        [
          { from: { glob: 'assets/**' } },
          { from: { glob: 'fonts/**' } },
          { from: { glob: '**/*.gif' } },
          { from: { glob: '**/*.jpg' } },
          { from: { glob: '**/*.png' } }
        ],
```

If you add the `.gif` line to the patterns it should bundle fine in your application and resolve when using a bundled app.
