### ISSUE TITLE
Plugin nativescript-gif is not included in preview app on device

### ISSUE THREAD

**Issue by TySabs** [bradmartin/nativescript-gif#35]
Great plugin. I need some help getting it to work with the iOS preview app.

I can get this plugin to work for an iOS emulator using `tns run ios --bundle` but it crashes when I try to use it with the iOS NativeScript playground app using the `tns preview --bundle` command. I have the FLAnimatedImageView added to my podfile. During compilation of preview, this error message is displayed: 

> Plugin nativescript-gif is not included in preview app on device 73997E1A-7203-4529-A00A-39498F9F42DE and will not work.

**Comment by TySabs** [comment]
Here is a stack trace of it crashing:

> LOG from device tyPhone: 2019-05-24 18:18:13.533 nsplaydev[24767:6449126] ***** Fatal JavaScript exception - application has been terminated. *****
2019-05-24 18:18:13.533 nsplaydev[24767:6449126] Native stack trace:
1   0x10519f3b0 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1051d0db4 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x105c35fa4 ffi_closure_SYSV_inner
4   0x105c381b4 .Ldo_closure
5   0x1c6d64188 <redacted>
6   0x1c6d646a8 <redacted>
7   0x1c6d2ffbc <redacted>
8   0x1c6d4db7c <redacted>
9   0x1c6fe1ddc <redacted>
10  0x198e5f454 <redacted>
11  0x19e17e488 <redacted>
12  0x19e17e774 <redacted>
13  0x19e0e628c <redacted>
14  0x19e114fbc <redacted>
15  0x19e115d48 <redacted>
16  0x199beaee8 <redacted>
17  0x199be59e0 <redacted>
18  0x199be5f40 <redacted>
19  0x199be5764 CFRunLoopRunSpecific
20  0x19be21dd4 GSEventRunModal
21  0x1c6b3c00c UIApplicationMain
22  0x105c38044 ffi_call_SYSV
23  0x105c356c4 ffi_call_int
24  0x105c351c0 ffi_call
25  0x105164b80 NativeScript::FunctionWrapper::call(JSC::ExecState*)
26  0x105c34268 llint_entry
27  0x105c336c4 llint_entry
28  0x105c336c4 llint_entry
29  0x105c336c4 llint_entry
30  0x105c336c4 llint_entry
31  0x105c336c4 llint_entry
2019-05-24 18:18:13.535 nsplaydev[24767:6449126] JavaScript stack trace:
2019-05-24 18:18:13.535 nsplaydev[24767:6449126] 1   Gif@file:///app/vendor.js:6914:47
2   createView@file:///app/tns_modules/nativescript-angular/view-util.js:215:33
3   createElement@file:///app/tns_modules/nativescript-angular/renderer.js:135:40
4   createElement@file:///app/tns_modules/nativescript-angular/renderer.js:412:55
5   createElement@file:///app/tns_modules/@angular/core/bundles/core.umd.js:24262:49
6   createElement@file:///app/tns_modules/@angular/core/bundles/core.umd.js:20985:44
7   createViewNodes@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23237:43
8   createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23184:24
9   callWithDebugContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:24198:34
10  createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:21765:60
11  createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:21631:57
12  _updateView@file:///app/tns_modules/@angular/common/bundles/common.umd.js:3670:67
13  set@file:///app/tns_modules/@angular/common/bundles/common.umd.js:3638:33
14  updateProp@file:///app/tns_modules/@angular/core/bundles/core.umd.js:22326:30
15  checkAndUpdateDirectiveInline@file:///app/tns_modules/@angular/core/bundles/core.umd.js:22077:33
16  debugCheckAndUpdateNode@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23980:47
17  debugCheckDirectivesFn@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23940:40
18  @:169:8
19  checkAndUpdateView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23328:34
20  callWithDebugContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:24198:34
21  detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:21709:44
22  detectChangesOnChild@file:///app/tns_modules/nativescript-angular/directives/templated-items-comp.js:147:30
23  onItemLoading@file:///app/tns_modules/nativescript-angular/directives/templated-items-comp.js:122:34
24  notify@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:107:37
25  notifyForItemAtIndex@file:///app/tns_modules/tns-core-modules/ui/list-view/list-view.js:48:20
26  _prepareCell@file:///app/tns_modules/tns-core-modules/ui/list-view/list-view.js:356:44
27  tableViewCellForRowAtIndexPath@file:///app/tns_modules/tns-core-modules/ui/list-view/list-view.js:71:31
28  UIApplicationMain@[native code]
29  _start@file:///app/tns_modules/tns-core-modules/application/application.js:277:26
30  run@file:///app/tns_modules/tns-core-modules/application/application.js:309:11
31  bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:205:26
32  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
33  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
34  @file:///app/bundle.js:8006:144
35  ./main.ts@file:///app/bundle.js:8011:34
36  __webpack_require__@file:///app/bundle.js:752:34
37  checkDeferredModules@file:///app/bundle.js:45:42
38  @file:///app/bundle.js:828:38
39  anonymous@file:///app/bundle.js:829:12
40  evaluate@[native code]
41  moduleEvaluation@[native code]
42  promiseReactionJob@[native code]
43  require@[native code]
44  anonymous@file:///app/starter.js:2:8
45  evaluate@[native code]
46  moduleEvaluation@[native code]
47  promiseReactionJob@[native code]
2019-05-24 18:18:13.535 nsplaydev[24767:6449126] JavaScript error:
file:///app/vendor.js:6914:47: JS ERROR ReferenceError: Can't find variable: FLAnimatedImageView
2019-05-24 18:18:13.536 nsplaydev[24767:6449126] PlayLiveSync: Uncaught Exception
2019-05-24 18:18:13.537 nsplaydev[24767:6449126] PlayLiveSync: Sending crash report
2019-05-24 18:18:17.539 nsplaydev[24767:6449126] *** JavaScript call stack:
(
	0   UIApplicationMain@[native code]
	1   _start@file:///app/tns_modules/tns-core-modules/application/application.js:277:26
	2   run@file:///app/tns_modules/tns-core-modules/application/application.js:309:11
	3   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:205:26
	4   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
	5   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
	6   @file:///app/bundle.js:8006:144
	7   ./main.ts@file:///app/bundle.js:8011:34
	8   __webpack_require__@file:///app/bundle.js:752:34
	9   checkDeferredModules@file:///app/bundle.js:45:42
	10  @file:///app/bundle.js:828:38
	11  anonymous@file:///app/bundle.js:829:12
	12  evaluate@[native code]
	13  moduleEvaluation@:1:11
	14  promiseReactionJob@:1:11
	15  require@[native code]
	16  anonymous@file:///app/starter.js:2:8
	17  evaluate@[native code]
	18  moduleEvaluation@:1:11
	19  promiseReactionJob@:1:11
)
2019-05-24 18:18:17.539 nsplaydev[24767:6449126] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: FLAnimatedImageView
 at 
1   Gif@file:///app/vendor.js:6914:47
2   createView@file:///app/tns_modules/nativescript-angular/view-util.js:215:33
3   createElement@file:///app/tns_modules/nativescript-angular/renderer.js:135:40
4   createElement@file:///app/tns_modules/nativescript-angular/renderer.js:412:55
5   createElement@file:///app/tns_modules/@angular/core/bundles/core.umd.js:24262:49
6   createElement@file:///app/tns_modules/@angular/core/bundles/core.umd.js:20985:44
7   createViewNodes@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23237:43
8   createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23184:24
9   callWithDebugContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:24198:34
10  createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:21765:60
11  createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:21631:57
12  _updateView@file:///app/tns_modules/@angular/common/bundles/common.umd.js:3670:67
13  set@file:///app/tns_modules/@angular/common/bundles/common.umd.js:3638:33
14  updateProp@file:///app/tns_modules/@angular/core/bundles/core.umd.js:22326:30
15  checkAndUpdateDirectiveInline@file:///app/tns_modules/@angular/core/bundles/core.umd.js:22077:33
16  debugCheckAndUpdateNode@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23980:47
17  debugCheckDirectivesFn@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23940:40
18  @:169:8
19  checkAndUpdateView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:23328:34
20  callWithDebugContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:24198:34
21  detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:21709:44
22  detectChangesOnChild@file:///app/tns_modules/nativescript-angular/directives/templated-items-comp.js:147:30
23  onItemLoading@file:///app/tns_modules/nativescript-angular/directives/templated-items-comp.js:122:34
24  notify@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:107:37
25  notifyForItemAtIndex@file:///app/tns_modules/tns-core-modules/ui/list-view/list-view.js:48:20
26  _prepareCell@file:///app/tns_modules/tns-core-modules/ui/list-view/list-view.js:356:44
27  tableViewCellForRowAtIndexPath@file:///app/tns_modules/tns-core-modules/ui/list-view/list-view.js:71:31
28  UIApplicationMain@[native code]
29  _start@file:///app/tns_modules/tns-core-modules/application/application.js:277:26
30  run@file:///app/tns_modules/tns-core-modules/application/application.js:309:11
31  bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:205:26
32  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
33  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
34  @file:///app/bundle.js:8006:144
35  ./main.ts@file:///app/bundle.js:8011:34
36  __webpack_require__@file:///app/bundle.js:752:34
37  checkDeferredModules@file:///app/bundle.js:45:42
38  @file:///app/bundle.js:828:38
39  anonymous@file:///app/bundle.js:829:12
40  evaluate@[native code]
41  moduleEvaluation@[native code]
42  promiseReactionJob@[native code]
43  require@[native code]
44  anonymous@file:///app/starter.js:2:8
45  evaluate@[native code]
46  moduleEvaluation@[native code]
47  promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x199c5b758 0x198e63d00 0x10519f7f4 0x1051d0db4 0x105c35fa4 0x105c381b4 0x1c6d64188 0x1c6d646a8 0x1c6d2ffbc 0x1c6d4db7c 0x1c6fe1ddc 0x198e5f454 0x19e17e488 0x19e17e774 0x19e0e628c 0x19e114fbc 0x19e115d48 0x199beaee8 0x199be59e0 0x199be5f40 0x199be5764 0x19be21dd4 0x1c6b3c00c 0x105c38044 0x105c356c4 0x105c351c0 0x105164b80 0x105c34268 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c336c4 0x105c2c12c 0x105a2cabc 0x105be6520 0x10517c570 0x1052bb268 0x105c3413c 0x105c3365c 0x105c336c4 0x105c2c12c 0x105a2cabc 0x105be6684 0x1052b6668 0x10517390c 0x105178c7c 0x105c3413c 0x105c336c4 0x105c2c12c 0x105a2cabc 0x105be6520 0x10517c570 0x1052bb268 0x105c3413c 0x105c336c4 0x105c336c4 0x105c2c12c 0x105a2cabc 0x105be6684 0x1052b6668 0x10517390c 0x1051dd930 0x1061cb3c8 0x104b6b3f0 0x1996a4ffc)
libc++abi.dylib: terminating with uncaught exception of type NSException
2019-05-24 18:18:17.540 nsplaydev[24767:6449126] PlayLiveSync: Uncaught Exception

**Comment by bradmartin** [comment]
Can't and won't work. Native dependencies must be included in the executable. Preview app cannot be modified in this manner since it's delivered via play store already signed as an apk.
