### ISSUE TITLE
could you show me how to stop gif????

### ISSUE THREAD

**Issue by niteofhunter** [bradmartin/nativescript-gif#36]
Hi! I'm novice in native script
I'm using this library, and it is works very well

But as I written in first line, I'm novice of native script that I don't know how to use api of library like this.

you write that user can stop gif file with "stop()" but I don't know how to use it

could you show me how to use your API?

Thanks! ^^

**Comment by bradmartin** [comment]
The demo app provides code examples https://github.com/bradmartin/nativescript-gif/blob/b70c8f4e44c125f664e896a5b5a19d1b4b18c0fc/demo/app/main-page.ts#L36

👍

**Comment by niteofhunter** [comment]
I have one more question


is it can work with "this.stop()"????


네이버 메일 앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Brad Martin" <notifications@github.com>
받는사람: "bradmartin/nativescript-gif" <nativescript-gif@noreply.github.com>
참조: "niteofhunter" <niteofhunter@naver.com>,"Author" <author@noreply.github.com>
날짜: 2019.07.02 오전 00:52:34 (GMT+10:00)
제목: Re: [bradmartin/nativescript-gif] could you show me how to stop gif???? (#36)

The demo app provides code examples https://github.com/bradmartin/nativescript-gif/blob/b70c8f4e44c125f664e896a5b5a19d1b4b18c0fc/demo/app/main-page.ts#L36
👍

**Comment by bradmartin** [comment]
Not unless you tried to override `this` and set it equal to a gif instance.

That is more a general programming question though 👍 nothing NativeScript specific. You can probably learn a lot from some intro javascript scope tutorials if you're unsure of what `this` is when executed in javascript.

**Comment by niteofhunter** [comment]
OH!!!! It's working now!!!
 
 
Thanks you!!!
 
you are my life saver
-----Original Message-----
