### ISSUE TITLE
Any plans to upgrade for NS 6.x?

### ISSUE THREAD

**Issue by demetrius-tech** [bradmartin/nativescript-gif#40]
Hi, I am getting some errors when adding to a NS 6 project. And it seems that the plug-in does not support NS 6.0 yet, right?

**Comment by bradmartin** [comment]
Demo updated and working without issue :) feel free to poke around on it to fix your issue, also important to note: https://github.com/bradmartin/nativescript-gif#bundling-note be sure you have webpack.config for your gifs in the globs so the files are in the bundle correctly.

**Comment by demetrius-tech** [comment]
Wow, demo works like charm. Thanks a lot, it was really quick.

**Comment by demetrius-tech** [comment]
Please update also the plugin on marketplace and npm repo #41

**Comment by bradmartin** [comment]
marketplace is just a link back to npm, it's not an official service of packages/artifacts. I believe it updates nightly. NPM was pushed out with a bug release bc I updated the native android lib to its latest bug release as well.  Hope it works well for you.
