### ISSUE TITLE
If I install using tns plugin it does not generate .ts files

### ISSUE THREAD

**Issue by demetrius-tech** [bradmartin/nativescript-gif#42]
I run: tns plugin add nativescript-gif

And the node_modules/nativescript-gif directory looks like this:

.
├── gif.android.js
├── gif.common.js
├── gif.ios.js
├── package.json
├── platforms
│   ├── android
│   │   └── include.gradle
│   └── ios
│       ├── Podfile
│       └── nativescriptgif
│           └── app
│               └── App_Resources
│                   └── iOS
│                       └── Info.plist
└── scripts
    └── build-native.js

8 directories, 8 files

**Comment by bradmartin** [comment]
Never should. They're not executable.
