### ISSUE TITLE
How I do operate this module with an Angular 2 app?

### ISSUE THREAD

**Issue by Yamilquery** [bradmartin/nativescript-gif#6]
How I do operate this module with an Angular 2 app?

**Comment by bradmartin** [comment]
I've not added a sample here but view the sample for other UI components, checkbox here https://github.com/bradmartin/nativescript-checkbox/blob/master/README.md#angular-usage-sample hope that helps.

**Comment by Yamilquery** [comment]
Thank's @bradmartin , but this don't work for me. It seems that the library is incompatible with Angular 2

**Comment by bradmartin** [comment]
It's compatible. Nothing to cause it not to work with angular. Just a
matter of how or what is causing your issue :) this is written with plain
NativeScript therefore unless there is a bug in the angular NativeScript
side it should work just fine. Hope that helps you going forward. Can you
add your markup, code, package.json, and errors here to help diagnose the
entire issue

**Comment by Yamilquery** [comment]
Thanks for your answer. However, it does not work, it simply does not display the Gif image.

I've even tried:
```
<Gif:Gif src="res://pac.gif" height="200"></Gif:Gif>
```
and:
`<Gif:Gif src="~/gifs/pac.gif" height="200"></Gif:Gif>`

But I can't see nothing...

I registered the item using this:

`RegisterElement ("Gif", () => require ("nativescript-gif").`

**Comment by bradmartin** [comment]
Can you provide the full register element code? Not sure if it's cut off on
my phone or if typo. I think you need to add the class at the end there if
its missing.

**Comment by Yamilquery** [comment]
Thank you very much for your tool.

I did this by changing it:
`<Gif src = "~ / gifs / pac.gif" height = "200"> </ Gif>`

🐎

**Comment by robcaa** [comment]
Can somebody help me? Don't work for me with angular.
Here is what I am doing:
Install:
`npm install nativescript-gif --save`
full restart:
`tns run android --emulator`

Registerelement in the component class (howto.component.ts):
```
import {registerElement} from "nativescript-angular/element-registry";
registerElement("Gif", () => require("nativescript-gif"));
```

View (howto.html):
```
<Gif src="~/App_Resources/Android/howto.gif"></Gif>
<Gif:Gif src="~/App_Resources/Android/howto.gif"/>
```

But nothing to work. 

The first (Gif src) causing this error:
Unhandled Promise rejection: error in pages/...html caused by: viewClass is not a constructor
The second (<Gif:Gif src): nothing happend

What's wrong?

**Comment by bradmartin** [comment]
Be sure to follow these steps outlined here
https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

**Comment by robcaa** [comment]
I can't send the beer, because don't work :(
Same result
Any other ideas?

**Comment by bradmartin** [comment]
Oh just dawned on me your path is incorrect. Items in app_resources are compiled into the app under `res://` try adjusting the path and see

**Comment by bradmartin** [comment]
So `res://how-to.gif` might be it

**Comment by robcaa** [comment]
No luck. Missing Image with resourceID: res://how-to.gif
but if I write this:
<Image src="~/App_Resources/Android/howto.gif"></Image>
The gif image is shown.

**Comment by bradmartin** [comment]
Personally I wouldn't put .gifs under app_resources. I would create a folder for this inside the main `app` folder and use the `~/gifs/how-to.gif` assuming a folder of `gifs` exists in the main app.

**Comment by robcaa** [comment]
I copied the file to app/gifs/howto.gif
rebuild the app
and try these:
`<Gif:Gif src="~/gifs/howto.gif" />` Nothing
`<Gif src="~/gifs/howto.gif"></Gif>` Object is not a constructor
`<Image src="~/gifs/howto.gif"></Image>`  image shown

**Comment by bradmartin** [comment]
Strange. I know it works as reported from the other guy on the issue. And I
have it running fine myself. Have you tried uninstalling, rebuilding and
then running after moving the files around?

**Comment by robcaa** [comment]
Unfortunately does not work :(
Is it good if I registerelement in the howto.component.ts not the app.component.ts?

howto.component.ts:
```
import { Component, ElementRef, OnInit, ViewChild, AfterViewInit } from "@angular/core";
import { Router } from "@angular/router";
import { Page } from "ui/page";

import {registerElement} from "nativescript-angular/element-registry";
registerElement("Gif", () => require("nativescript-gif"));

@Component({
  selector: "howto",
  templateUrl: "pages/howto/howto.html",
  styleUrls: []
})

export class HowtoComponent implements OnInit {
    constructor(private router: Router, private page: Page) {
    }
    ngOnInit() {
        this.page.actionBarHidden = true;
    }
    navigate(where: String) {
        this.router.navigate(["/"+where]);
    }
}
```

howto.html:
```
<Image src="~/gifs/howto.gif"></Image>
<Gif:Gif src="~/gifs/howto.gif" />
<Gif src="~/gifs/howto.gif"></Gif>
```

**Comment by bradmartin** [comment]
I can't answer any angular questions, not my specialty 😄 . Could you try a remote .gif to make sure it's not something wrong with the .gif in your app. Here is a url to try https://media.giphy.com/media/d3bRxZgHLFvAmehW/giphy.gif

**Comment by bradmartin** [comment]
@robcaa - see here for angular 2 sample from Nathan Walker's app. 
Maybe it'll help you figure out your issue: https://github.com/NathanWalker/ShoutOutPlay/tree/development/app/components/intro 

Let me know if that helps any.

**Comment by robcaa** [comment]
Remote gif does not work :(

To check Nathan Walker's app is a good idea.
I found two differences between my and Nathen app:
1.:
myCode: `registerElement("Gif", () => require("nativescript-gif"));`
Nathen code: `registerElement("Gif", () => require("nativescript-gif").Gif);`
2.:
I use registerElement in a sub component. Nathen use in the app.component.ts.



I try these modifications but the gif not appear, and I give these errors:
In the console:

> 01-14 22:04:32.655  3770  3770 W System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
> 01-14 22:04:32.655  3770  3770 W System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
> 01-14 22:04:32.655  3770  3770 W System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
> 01-14 22:04:32.655  3770  3770 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:895)
> 01-14 22:04:32.655  3770  3770 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:879)
> 01-14 22:04:32.655  3770  3770 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:871)
> 01-14 22:04:32.656  3770  3770 W System.err:    at com.tns.Runtime.callJSMethodNative(Native Method)
> 01-14 22:04:32.657  3770  3770 W System.err:    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
> 01-14 22:04:32.657  3770  3770 W System.err:    at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
> 01-14 22:04:32.657  3770  3770 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:895)
> 01-14 22:04:32.657  3770  3770 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:879)
> 01-14 22:04:32.657  3770  3770 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:871)

In the emulator:
![image](https://cloud.githubusercontent.com/assets/1994329/21958436/88ff3468-daae-11e6-850e-2c0be489cdce.png)

"Failed to open given input", but I try remote gif, local gif, resource gif.

**Comment by bradmartin** [comment]
Can you try cloning the repo and running the sample app? If it works fine
then we know the issue is something in your app

**Comment by bradmartin** [comment]
Well nevermind sample isn't angular.

**Comment by bradmartin** [comment]
Oh and that error from the native lib method with message - failed to open given input sounds like some permission issue or failure with the gif itself. Might want to post on the NativeScript forums and see if anyone has some time to help investigate the issue. I can't get an error with plain NativeScript and the gif works for Walker and several other apps I've seen post about using the gif on slack and the original author of this issue. So it's hard to say what's going on unfortunately :(

**Comment by bradmartin** [comment]
Maybe found something here
https://github.com/koral--/android-gif-drawable#upgrading-from-123 try
adjusting the build.gradle in the plugin folder in node_modules to a
specific version. Create a build, uninstalling the old app before running
the new build and see if that fixes the error.

**Comment by robcaa** [comment]
What a beautiful day :D
Your suggestion is worked!
Here is the beer: ![beer](http://www.iconsplace.com/icons/preview/orange/beer-32.png)

What I modify:
\node_modules\nativescript-gif\platforms\android\include.gradle
In Line 15:
`compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.17'`
I changed the version to 1.2.3:
`compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.3'`

And works, all. Locally and remote gifs.
Thanks the many many helps!

**Comment by bradmartin** [comment]
Thanks for confirming. Need to make sure this gets updated in the plugin.

**Comment by sulymkaa** [comment]
facing the same issue with nativescript-angular": "7.0.0"
include.gradle contains:
     compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.15'
issue need to be reopened

**Comment by BJacob7** [comment]
hi guys for me the solution was to create a folder under the name gifs inside  the folder "app" 
and copy the gifs files to the gifs folder..
in html its should be like this :
            <Gif src="~/gifs/gif_pro" height="200"></Gif>
in ts ;
import { registerElement } from 'nativescript-angular/element-registry';
import { Gif } from 'nativescript-gif';
registerElement('Gif', () => Gif);
@bradmartin 
@robcaa

**Comment by mrwrighty** [comment]
I'm having issues with this on core javascript app. I have tried the images folder under app and also a folder called gifs. Every time I load I get Caused by: pl.droidsonroids.gif.GifIOException: GifError 101: Failed to open given input: No such file or directory.

I have loaded an image from both the images and gifs folder so I know my path is correct. I use cannot get the gifs to load.

`  <Gif:Gif row="0" src="~/gifs/animation.gif"/>`

**Comment by NazimMertBilgi** [comment]
> Temel javascript uygulamasında bununla ilgili sorunlar yaşıyorum. Ben app altında görüntüleri klasörü ve ayrıca gif denilen bir klasör denedim. Her yüklediğimde Neden: pl.droidsonroids.gif.GifIOException: GifError 101: Verilen girdi açılamadı: Böyle bir dosya veya dizin yok.
> 
> Hem görüntüler hem de gifler klasöründen bir resim yükledim, böylece yolumun doğru olduğunu biliyorum. Ben gif yüklemek için kullanamıyorum kullanın.
> 
> ` <Gif:Gif row="0" src="~/gifs/animation.gif"/>`

same problem.
