### ISSUE TITLE
Source empty when used with angular binding and RadListView

### ISSUE THREAD

**Issue by tiste** [bradmartin/nativescript-gif#7]
Hey,

First, thanks for you lib :)

I succeeded to make your lib work with angular stuff:

`registerElement('Gif', () => require('nativescript-gif').Gif);`

But, I experienced some issues when used with `RadListView`. The `src` property seems to be undefined.

Here's my html view:

```
<RadSideDrawer>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideStackLayout">
            <Label text="My sounds" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="First" class="sideLabel"></Label>
            <Label text="Second" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>

    <GridLayout tkMainContent>
        <RadListView [items]="sounds">
            <template tkListItemTemplate let-item="item">
                <StackLayout orientation="vertical" class="item-template-style">
                    <Gif [src]="item.cover" height="100"></Gif>
                    <Label [text]="item.cover"></Label>
                </StackLayout>
            </template>

            <ListViewStaggeredLayout tkListViewLayout scrollDirection="Vertical"
                                     spanCount="3"></ListViewStaggeredLayout>
        </RadListView>
    </GridLayout>
</RadSideDrawer>
```

Do you have any ideas to make the gif appears instead of `No src value detected.` message?

**Comment by mourice** [comment]
I am getting the same error for angular2 Nativescript application any solution?

**Comment by bradmartin** [comment]
I've never tried using the gif in a listview so I'm not sure. Have you determined this is specific to the RadListView? If not, could you try with the core ListView and see if it works? If it does then we would need to make sure to link in the Telerik UI team so they can figure out what the RadListView is doing to cause the issue.

**Comment by mourice** [comment]
After debug I noticed that onloaded event of the gifview gets called before any other event so assigning the gif src via databinding not casusing the onload to fire again thus getting the empty src. If I call gifview.0nloaded after src is set then gif gets displayed. Though This is not specific to the listview.

**Comment by bradmartin** [comment]
Thanks @mourice - not sure I follow the logic you describe above. I'm a visual guy so seeing the code helps me more 😄

**Comment by 98falcon** [comment]
Any solution to display with angular binding?
in my case my xml file looks like this
`<Gif src="{{url}}" height="300"> </Gif>`

**Comment by bradmartin** [comment]
This is working for Nathan Walker in a production app - https://github.com/NathanWalker/ShoutOutPlay/blob/development/app/components/intro/intro.component.html#L27 @98falcon - it's not in a RadListView but the binding should work.

**Comment by 98falcon** [comment]
@bradmartin  thanks got it working! But it isn't working with a dynamic src, like when I get a random src from the server it doesn't change the gif, it stays on the same gif. any idea? also
any api use exemple? sorry im kinda new to angular 2...
Thanks!

**Comment by bradmartin** [comment]
It should change the src - https://github.com/bradmartin/nativescript-gif/blob/master/gif.common.ts#L18
but might need to improve the way it's configured. I don't recall testing it. As for an api example - you can set the `src` value to a remote url for a .gif file and it should render it. If you need more help on wiring up an API the NS slack community is awesome as well as the forums to discuss things like that :) easier to keep the plugin repo clean 👍

**Comment by rsquared86** [comment]
did anyone figure out how to load dynamic src? I still get no src detected when i try to set it from an observable firebase record. If i hard code the url, the gif works fine.

**Comment by pandabamboo90** [comment]
@tiste Thanks for your sharing !!! 

I had the problem `Cannot find module 'nativescript-gif'` while follow README docs for using this plugin with NS Angular.

This `registerElement('Gif', () => require('nativescript-gif').Gif);` resolved the issue.
